name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        # Install build essentials and CMake
        sudo apt-get install -y cmake g++ make
        # Install Protocol Buffers
        sudo apt-get install -y protobuf-compiler libprotobuf-dev
        # Install nlohmann-json
        sudo apt-get install -y nlohmann-json3-dev
        # Install Paho MQTT for examples
        sudo apt-get install -y libpaho-mqtt-dev libpaho-mqttpp-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
